Tests for GelPad and ContactGroup
lhmcgann/EStimLibrary pull request #35
Opened 2024-10-14 21:34 UTC by fernthao

2024-10-16 16:53 UTC, Blubby24 submitted a review, later dismissed

2024-10-28 20:34 UTC, lhmcgann requested changes
Nice job! Mostly just some tiny style and commenting things and should be good to go!

2024-10-28 20:34 UTC, lhmcgann commented on EStimLibrary.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "tests", "tests", "{6EED0CF2-4443-42D5-8562-2DF5D5697266}"
Ah, undo changes to the EStimLibrary.sln file. The tests/EStimLibrary.UnitTests/EStimLibrary.UnitTests.sln file should already open both the EStimLibrary source code project and the unit test project

2024-10-28 20:34 UTC, lhmcgann commented on src/EStimLibrary/Extensions/HardwareInterfaces/ContactGroup.cs
> +        if (numContacts > 0) this._NumContacts = numContacts;
Just a style thing here: make use of whitespace for readability! So it would be like:
```
if (...)
{
    this._NumContacts = ...;
}
else
{
    throw new ...;
}
```

2024-10-28 20:34 UTC, lhmcgann commented on src/EStimLibrary/Extensions/HardwareInterfaces/ContactGroup.cs
>      public ContactGroup(int numContacts) : base()
Add doc comments to each class and method as you're going, so for this constructor might be:
```
/// <summary>
/// Create a contact group with a positive integer number of contacts.
/// </summary>
/// <param name="numContacts">TODO</param>
/// <exception cref="ArgumentException">TODO</exception>
```

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +namespace EStimLibrary.UnitTests.Extensions.HardwareInterfaces
Convention thing: you can add a ; at the end of this namespace line, then if they don't automatically disappear, you should be able to remove the outermost {} and un-indent everything once

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +using System.ComponentModel.DataAnnotations;
May be able to remove this using statement

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +        /// </summary>
Tiny tiny style thing: I think you have some extra spaces in front of "Make" and "Number"?

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +            //Assert (Test if initialized params are correct)
Another tiny style thing: add a space between the // and the first word

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +        /// </summary>
Also just a typo: "Number of contact**s**"

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +        // Test valid (positive) values for num contacts.
Just include this comment in the summary comment

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +        // Test invalid parameter values, expect object to fail to be created
Move to a summary doc comment above the [Theory] flag and also include the <param name="numContacts">TODO<param> in that doc comment

2024-10-28 20:34 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/HWInterfacesTests.cs
> +using System.ComponentModel.DataAnnotations;
Just to match the directory structure of the EStimLibrary itself, you're going to want the test project to look like this once you're done:
EStimLibrary.UnitTests/
    Core/
        <whatever was in here>
    Extensions/
        HardwareInterfaces/
            ContactGroupTests.cs
            GelPadTests.cs

So 2 test files, one per source code file you're testing, and both files in a HardwareInterfaces subfolder of Extensions/

2024-10-28 20:40 UTC, lhmcgann commented
Also, if you're able to make sure all the classes, properties, fields, and methods in the source code classes have doc strings, that will be super helpful so we don't have to go back through the whole library at the end

2024-11-18 19:50 UTC, lhmcgann submitted a review, later dismissed

2024-11-18 20:01 UTC, merged

2024-11-18 20:11 UTC, lhmcgann commented
addressed #31