String hierarchy spec testing
lhmcgann/EStimLibrary pull request #49
Opened 2024-11-04 23:46 UTC by drmannequin

2024-11-08 16:02 UTC, lhmcgann commented
Make sure to edit the PR to merge onto release not main

2024-11-11 03:13 UTC, cld99 commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
Make sure to update your test progress tracker at the top to reflect that GetHashCode and ToString have been tested. You may also want to test more types of malformed inputs for ParseFullSpec, ParseRegionSpec, and ParseModifierSpec (i.e., extra delimiters and other inputs that do not follow the required convention). Should RegionSetOverlaps and ModifiersAllowOverlap retrun true for partial overlaps (as RegionSetOverlaps seems to operate), or just full overlap of the shorter specification (as ModifiersAllowOverlap seems to operate and as the comments within the methods indicate)? Depending on which is correct, method comments/behavior should probably be adjusted to be consistent. Testing for TryGetOverlap should probably include tests for overlapping modifier sets without overlapping regions just to make sure that it works as expected. Also, shouldn't the expected overlapping region for the second test of TryGetOverlap_ShouldIdentifyOverlapIsPossible just be "region1 | modifier1"? Testing for Equals should probably include tests for different orderings of the regions, since the ordering does matter for those. Likewise for GetHashCode, which you based the testing on for consistency with the Equals method. Other than these small nitpicks, everything looks good!

2024-11-11 03:15 UTC, cld99 submitted a review, later dismissed
I left comments on the StringHierarchySpecTest file detailing some small nitpicks, but everything looks to be functioning properly and ready to merge.

2025-01-17 19:59 UTC, lhmcgann commented
Ok @drmannequin I refactored/reimplemented the TryGetOverlap and associated functions in StringHierarchySpec. It resulted in me moving those methods and that overall functionality to StringHierarchyBodyModel, so the test cases are commented out. You can leave them like that in your test class until you get to testing the body model, but just test all the other StringHierarchySpec methods for now. Lmk if you want to chat, get any clarification, etc.

2025-03-10 20:42 UTC, lhmcgann requested changes

2025-03-10 20:42 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchySpec.cs
> +        out string baseName, out string option)
This should be "options", e.g., "left index finger" should be valid where "finger" is the region basename and "left index" is the option string for that region. Forgive me if I made these changes making it now incorrect, but (1) it should be reverted back to what is in red. (2) Add a test case or so for this case. (3) Write a method in StringHierarchySpec called TryParseOptions() that uses the OPTIONS_REGION_DELIMITER to split an "options" string as output by TryParseOptionedRegionName, returning a bool (true if any options found, else false) and outputting (via an `out` param) the string[] of option names. Should handle an empty, single option, and multi-option-containing string. Should also trim whitespace from each option name found. (4) Write test cases for that function too.

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +namespace EStimLibrary.UnitTests.Extensions.SpatialModel.StringHierarchy;
I changed it here, but calling attention to it so you know in future: use filscoped namespace syntax, i.e., just put a ; at the end of the namespace line so you don't need the extra {} around the whole body of the file and don't need to indent that extra level.

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +    public void ConstructorFullSpec_ValidInputs_ShouldInit(string fullSpec,
Try to have test functions follow the format described in the "Our Coding Practices" page in our OneNote: <CLassMethoBeingTested>_<Scenario>_Should<ExpectedOutcome>. I know I also have the note in there you can exclude the <Scenario> bit if using [Theory] tags since there are multiple specific scenarios, but if all those specific scenarios fit into a more general scenario, e.g., "ValidInputs" like you kinda already have in you "Should<...>" section, just make that th <Scenario> piece.

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +        string[] expectedRegions, string[] expectedModifiers)
I'm also getting 2 failed test cases for this test method. Should be a simple fix of making the expected values lowercase

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +    /// Test the constructor StringHierarchySpec(string fullSpec), where the
Other style things I started fixing but will let you finish (Ik nit-picky and maybe tedious, but I'm being annoying about it now so we get in the habit of doing it in the first place): try to have lines be <= 80 characters and enter/indent after that. This is to help readability.

If [InlineData()] cases are multi-line too, just put the comments in a line on top of them rather than at the end of the last line. That way can read top-down and know what's coming.

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +    public void ToString_ShouldReturnFullSpecRepresentation(
All internal representations should be stored as lowercase since they go through the Parse...() methods when the object is constructed. --> Why are these uppercase "expected" values succeeding? --> May be a bug somewhere that needs fixing

2025-03-10 20:42 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchySpec.cs
>      public virtual bool Equals(StringHierarchySpec? other)
Check the coverage report for Equals() and GetHashCode(). I think just a few test cases missing to do with when "other" is null.

2025-03-10 20:42 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchySpec.cs
> +    /// <summary>
Add doc comments to:
- overall class
- properties
- methods

2025-03-10 20:42 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchySpecTests.cs
> +    public void ParseFullSpec_ShouldParseWithExpectedInputs(string fullSpec, string[] expectedRegions, string[] expectedModifiers)
Test cases to add:
- regions with options: different numbers of options, different regions in the path with or without options
- extra whitespace, e.g., before commas (I think you have this already), between option and region base names
- also some expected to fail test cases, e.g., when there are multiple | delimiters or other "dumb user behavior" examples --> what is the expected system behavior given those inputs? are they handled accordingly? "failing" here can also mean parsing the spec semantically incorrectly (i.e., not what the user meant) but what is syntactically correct

2026-03-23 00:01 UTC, merged