Test StringHierarchy Area and Location Factories
lhmcgann/EStimLibrary pull request #57
Opened 2024-11-18 20:52 UTC by cld99

2025-01-15 20:45 UTC, lhmcgann requested changes

2025-01-15 20:45 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +            $"and excluding the []:\n{baseModelRegion?.ToString() ?? "null"}";
In which cases were you finding baseModelRegion was null? It should always have a value after object initialization, so we don't really want to allow the possibility that it's null.

2025-01-15 20:45 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +        return parts.Length < 3 &&
For which cases was this change needed? What was failing? May be a larger bug/flaw

2025-01-15 20:45 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +            subregion.IsValidModifierSpec(parts[1]) : true);
Just curious: did adding the parens change the functionality and fix something or was this just a style clean?

2025-01-15 20:45 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
Same comments/questions in this file as in AreaFactory

2025-01-15 20:45 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
Please add doc comments to the source class, properties, and methods too

2025-01-15 20:45 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactoryTests.cs
> +    public void Constructor_ShouldAcceptNull()
We actually want to disallow null input. Is the current implementation (pre your related changes in the source code files above) allowing it?

2025-01-15 20:45 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactoryTests.cs
> +    public void TryCreate_ShouldValidateShouldMaybeCreate()
What is the "ShouldMaybe"? Are there some test values for which it should vs would not create? In that case, put them in separate test functions. This will be made easier by using [Theory] rather than [Fact] flags and then just having a bunch of different [InlineData()] test input options or all of them in one [MemberData()] flag. See some of the test classes merge into the hardware or release branch for examples. Restructuring to use these may or may not change which test methods you actually have, e.g., giving you one test method per condition tested, e.g., TryCreate_ValidatedValidParamsShouldCreate, TryCreate_UnvalidatedValidParamsShouldCreate, TryCreate_ValidatedInvalidParamsShouldFail. Then the different input values you give are different examples of each condition

2025-01-15 20:45 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactoryTests.cs
Same comments as in AreaFactory tests

2025-01-15 20:45 UTC, lhmcgann commented on docs/images/association_arrows-techvidvan.png
Are you by chance able to undo these changes to the image files? They have already been pushed in release which I know you aren't merging into yet, so if not possible it's alright we'll deal with it later, but if you can it will help prevent merge conflicts later.

2025-01-28 21:02 UTC, drmannequin reviewed
If null shouldn't be an acceptable parameter then an exception should be thrown if we try to pass null to it. Also it would be more clear to seperate the test cases in the TryCreate_ShouldValidateShouldMaybeCreate to seperate when it should create from when it shouldn't to reduce ambiguity.

2025-01-28 21:02 UTC, johnshi314 commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +            $"and excluding the []:\n{baseModelRegion?.ToString() ?? "null"}";
I think baseModelRegion will only be null if it's passed to the constructor as null. If it should never be null, it would be better to throw an exception instead.

2025-01-28 21:02 UTC, johnshi314 commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactoryTests.cs
> +    public void Constructor_ShouldAcceptNull()
The modified constructor treats null as an acceptable parameter. If we don't want this we should throw an exception in the constructor instead.

2025-01-30 17:17 UTC, cld99 commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +            subregion.IsValidModifierSpec(parts[1]) : true);
Yes, it first caused an error with the empty string test at lines 249-251 of StringHierarchyAreaFactoryTests. It looks like the conditional operator has lower precedence than &&, so assuming that we don't want all of the previous checks to default the output to true if they are false, the parentheses are necessary.

2025-01-30 18:32 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactory.cs
> +        return parts.Length < 3 &&
per discussion: include both this and > 0

2025-03-11 03:44 UTC, lhmcgann requested changes

2025-03-11 03:44 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +        return parts.Length > 0 && parts.Length < 3 &&
Use StringHierarchySpec.ParseFullSpec() here (and in the corresponding Area function) since that is the fullSpec parse and validation logic. I believe that logic just ignores any extra parts rather than erroring, so want to stay consistent.

2025-03-11 03:44 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +        out ILocation? product, bool skipValueValidation = false)
Added ? to indicate this output param could be null, an added ! in the function body to suppress null warnings (since the function value is passed to can handle null values, or value will have been checked to be non-null by the time it has used). You will need to similarly use ? and ! in the test classes to declare variables that could be null (i.e., your variables for output params) and suppress null value warnings (in my VSCode, all the places warnings appear show as yellow-underlined which could help identify them). I started changing some places in the SHLocationFactoryTests.cs class, but only barely --> will need to do the rest

2025-03-11 03:44 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyAreaFactoryTests.cs
> +                new StringHierarchyAreaFactory(null!);
Example of ! use

2025-03-11 03:44 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactoryTests.cs
> +        ILocation? product;
Example of ? use

2025-03-11 03:44 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactoryTests.cs
> +    public void Constructor_NonNull_ShouldInit()
If it doesn't make the test method name too long, try keeping to this <MethodName>_<Scenario>_Should<ExpectedBehavior/Output> format

2025-03-11 03:44 UTC, lhmcgann commented on tests/EStimLibrary.UnitTests/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactoryTests.cs
> +        Dictionary<string, object> paramValues1 =
Since you've written all the test cases this way already, fine for this PR, but in future, if you find yourself testing a whole bunch of different variations of data within the same test method, try to use a [Theory] tag with [InlineData()] or [MemberData()] instead

2025-04-15 16:38 UTC, cld99 commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +        return parts.Length > 0 && parts.Length < 3 &&
ParseFullSpec parses the component region and modifier specs, however this is already handled within the calls to TryGetSubregion and IsValidModifierSpec respectively, so unless we want to reconstruct the region and modifier specs, this will not be feasible. This function specifically errors if extra parts are included because (at least as specified in the doc comments) the spec passed in must contain a single region and at most one modifier set.

2025-04-24 16:47 UTC, lhmcgann approved these changes
Great job! Just made a few organizational edits (used MemberData tags to condense and make a little more readable) and have one curiosity question, but good to go!

2025-04-24 16:47 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +    /// <exception cref="NullReferenceException">Thrown if the base region is
what within this throws the exception? Is it just the ToString() call in generating the help msg?

2025-04-24 17:19 UTC, cld99 commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +    /// <exception cref="NullReferenceException">Thrown if the base region is
Yes, it is just the ToString() call if a null baseModelRegion is passed in.

2025-04-24 17:20 UTC, lhmcgann commented on src/EStimLibrary/Extensions/SpatialModel/StringHierarchy/StringHierarchyLocationFactory.cs
> +    /// <exception cref="NullReferenceException">Thrown if the base region is
yes :) could add an explicit null check in future

2026-03-21 02:32 UTC, merged